"""
Contract tests for the train-prompt workflow integration.

Validates that the integration is structured correctly — i.e. that no
manually-copied upstream files exist in the repository, that all automation
uses the proper tooling (gh aw, sparse git clone), and that repo-specific
files are in the right shape.

These tests deliberately do NOT check for the presence of files that are
fetched at runtime (e.g. train-prompt.lock.yml, .github/agents/,
tools/agent-skills-mcp/agent_skills_mcp.py).  Those files are generated or
fetched by post-start.sh / sync-from-upstream.yml and are gitignored.
"""
from __future__ import annotations

import pathlib
import re
import shutil
import stat
import subprocess

import pytest


REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------

def _gitignored(rel_path: str) -> bool:
    """Return True if the path is gitignored in this repository."""
    result = subprocess.run(
        ["git", "check-ignore", "--quiet", rel_path],
        cwd=REPO_ROOT,
        capture_output=True,
    )
    return result.returncode == 0


# ---------------------------------------------------------------------------
# Runtime-fetched files must be gitignored (never committed as copies)
# ---------------------------------------------------------------------------

RUNTIME_FETCHED = [
    # Managed by gh aw add / gh aw update
    ".github/workflows/train-prompt.lock.yml",
    ".github/workflows/train-prompt.md",
    ".github/workflows/shared/agent-skills-runtime.md",
    ".github/workflows/shared/trainer-loop-contract.md",
    # MCP server source — sparse-checked-out by post-start.sh
    "tools/agent-skills-mcp/agent_skills_mcp.py",
    "tools/agent-skills-mcp/server.py",
    "tools/agent-skills-mcp/uv.lock",
]


@pytest.mark.parametrize("rel_path", RUNTIME_FETCHED)
def test_runtime_fetched_file_is_gitignored(rel_path: str) -> None:
    """Runtime-fetched files must be gitignored so they can never be
    accidentally committed as manually-synced copies."""
    assert _gitignored(rel_path), (
        f"{rel_path} is NOT gitignored.\n"
        "Files fetched at runtime (by post-start.sh or gh aw) must be "
        "listed in .gitignore so they are never committed as manual copies."
    )


@pytest.mark.parametrize("rel_path", RUNTIME_FETCHED)
def test_runtime_fetched_file_not_tracked(rel_path: str) -> None:
    """Runtime-fetched files must not be tracked by git."""
    result = subprocess.run(
        ["git", "ls-files", rel_path],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    assert result.stdout.strip() == "", (
        f"{rel_path} is tracked by git — it must be removed.\n"
        "Run: git rm --cached {rel_path}"
    )


# ---------------------------------------------------------------------------
# .github/agents/ must be entirely gitignored (no manually-committed agents)
# ---------------------------------------------------------------------------

def test_github_agents_dir_is_gitignored() -> None:
    """The .github/agents/ directory must be gitignored so agent files
    generated by `gh aw add` are never committed as static copies."""
    assert _gitignored(".github/agents/trainer.agent.md"), (
        ".github/agents/ is not gitignored.\n"
        "Agent files are managed by `gh aw add`/`gh aw update` and must "
        "not be committed as manually-synced copies."
    )


# ---------------------------------------------------------------------------
# Repo-specific files must exist
# ---------------------------------------------------------------------------

REPO_SPECIFIC = [
    ".github/workflows/sync-from-upstream.yml",
    ".github/workflows/copilot-setup-steps.yml",
    ".github/workflows/shared/repo-runtime-context.md",
    ".devcontainer/post-start.sh",
    ".devcontainer/devcontainer.json",
    ".devcontainer/docker-compose.yml",
    "tools/agent-skills-mcp/pyproject.toml",
]


@pytest.mark.parametrize("rel_path", REPO_SPECIFIC)
def test_repo_specific_file_exists(rel_path: str) -> None:
    """Repo-specific files must be committed and present."""
    assert (REPO_ROOT / rel_path).is_file(), (
        f"{rel_path} is missing — it is repo-specific and must be committed."
    )


# ---------------------------------------------------------------------------
# No manual sync script
# ---------------------------------------------------------------------------

def test_no_manual_sync_script() -> None:
    """There must be no script that manually downloads/copies upstream files.
    Use `gh aw update train-prompt` instead."""
    assert not (REPO_ROOT / ".github" / "scripts" / "sync-upstream.sh").exists(), (
        ".github/scripts/sync-upstream.sh must not exist.\n"
        "Use `gh aw update train-prompt` in sync-from-upstream.yml instead."
    )


# ---------------------------------------------------------------------------
# sync-from-upstream.yml uses gh aw, not curl/wget
# ---------------------------------------------------------------------------

def test_sync_workflow_uses_gh_aw() -> None:
    """The sync workflow must use gh aw update/add, not curl or wget."""
    workflow = (
        REPO_ROOT / ".github" / "workflows" / "sync-from-upstream.yml"
    ).read_text()
    assert "gh aw update" in workflow or "gh aw add" in workflow, (
        "sync-from-upstream.yml must use `gh aw update` or `gh aw add`."
    )


def test_sync_workflow_no_curl_downloads() -> None:
    """The sync workflow must not curl/wget upstream source files directly.
    It must delegate entirely to `gh aw update`/`gh aw add`."""
    workflow = (
        REPO_ROOT / ".github" / "workflows" / "sync-from-upstream.yml"
    ).read_text()
    # Must not contain raw download commands for upstream files
    assert "curl" not in workflow, (
        "sync-from-upstream.yml must not use curl to download upstream files."
    )
    assert "wget" not in workflow, (
        "sync-from-upstream.yml must not use wget to download upstream files."
    )
    assert "sync-upstream.sh" not in workflow, (
        "sync-from-upstream.yml must not call sync-upstream.sh (it was removed)."
    )


# ---------------------------------------------------------------------------
# post-start.sh uses gh aw (not manual downloads for workflow/agents)
# ---------------------------------------------------------------------------

def test_post_start_uses_gh_aw_for_workflow() -> None:
    """post-start.sh must use `gh aw add`/`gh aw update` to install the
    workflow, not curl or manual file copying."""
    script = (REPO_ROOT / ".devcontainer" / "post-start.sh").read_text()
    assert "gh aw add" in script or "gh aw update" in script, (
        "post-start.sh must use `gh aw add` or `gh aw update` to install "
        "the train-prompt workflow."
    )


def test_post_start_fetches_mcp_source_from_upstream() -> None:
    """post-start.sh must fetch the MCP server source from upstream at
    runtime (not assume it is already committed)."""
    script = (REPO_ROOT / ".devcontainer" / "post-start.sh").read_text()
    # Must reference the upstream repo
    assert "copilot-auto-training" in script, (
        "post-start.sh must reference the upstream repo to fetch MCP source."
    )
    # Must use git clone or curl (not assume files are pre-committed)
    assert "git clone" in script or "curl" in script, (
        "post-start.sh must download the MCP source at runtime "
        "(git clone or curl), not assume it is committed."
    )


def test_post_start_installs_gh_aw() -> None:
    script = (REPO_ROOT / ".devcontainer" / "post-start.sh").read_text()
    assert "gh extension install" in script or "gh extension upgrade" in script


def test_post_start_installs_act() -> None:
    script = (REPO_ROOT / ".devcontainer" / "post-start.sh").read_text()
    assert "nektos/act" in script


def test_post_start_runs_uv_sync_for_mcp() -> None:
    """post-start.sh must run `uv sync` for the MCP server venv."""
    script = (REPO_ROOT / ".devcontainer" / "post-start.sh").read_text()
    assert "uv sync" in script and "agent-skills-mcp" in script


# ---------------------------------------------------------------------------
# MCP pyproject.toml is repo-specific (no trainer-skill bundling)
# ---------------------------------------------------------------------------

def test_mcp_pyproject_no_trainer_skill_bundling() -> None:
    """Our pyproject.toml must not bundle the upstream trainer skills."""
    import tomllib

    pyproject_path = REPO_ROOT / "tools" / "agent-skills-mcp" / "pyproject.toml"
    with pyproject_path.open("rb") as fh:
        data = tomllib.load(fh)

    force_include = (
        data.get("tool", {})
        .get("hatch", {})
        .get("build", {})
        .get("targets", {})
        .get("wheel", {})
        .get("force-include", {})
    )
    trainer_keys = [k for k in force_include if "trainer-" in k or "researcher-" in k]
    assert not trainer_keys, (
        f"pyproject.toml must not bundle upstream trainer skills: {trainer_keys}"
    )


# ---------------------------------------------------------------------------
# devcontainer config
# ---------------------------------------------------------------------------

def test_devcontainer_has_gh_cli_feature() -> None:
    import json
    dc = json.loads((REPO_ROOT / ".devcontainer" / "devcontainer.json").read_text())
    features = dc.get("features", {})
    assert any("github-cli" in k for k in features), (
        "devcontainer.json must include ghcr.io/devcontainers/features/github-cli"
    )


def test_devcontainer_has_uv_feature() -> None:
    import json
    dc = json.loads((REPO_ROOT / ".devcontainer" / "devcontainer.json").read_text())
    features = dc.get("features", {})
    assert any("uv" in k.lower() or "astral" in k.lower() for k in features), (
        "devcontainer.json must include the astral.sh-uv devcontainer feature"
    )


def test_devcontainer_calls_post_start() -> None:
    import json
    dc = json.loads((REPO_ROOT / ".devcontainer" / "devcontainer.json").read_text())
    assert "post-start.sh" in dc.get("postStartCommand", "")


def test_devcontainer_has_storage_requirement() -> None:
    import json
    dc = json.loads((REPO_ROOT / ".devcontainer" / "devcontainer.json").read_text())
    assert dc.get("hostRequirements", {}).get("storage"), (
        "devcontainer.json must set hostRequirements.storage for act"
    )


def test_docker_compose_mounts_docker_socket() -> None:
    compose = (REPO_ROOT / ".devcontainer" / "docker-compose.yml").read_text()
    assert "/var/run/docker.sock" in compose, (
        "docker-compose.yml must mount /var/run/docker.sock for act"
    )


# ---------------------------------------------------------------------------
# copilot-setup-steps.yml
# ---------------------------------------------------------------------------

def test_copilot_setup_runs_post_start() -> None:
    workflow = (
        REPO_ROOT / ".github" / "workflows" / "copilot-setup-steps.yml"
    ).read_text()
    assert "post-start.sh" in workflow


def test_copilot_setup_verifies_gh_aw() -> None:
    workflow = (
        REPO_ROOT / ".github" / "workflows" / "copilot-setup-steps.yml"
    ).read_text()
    assert "gh aw" in workflow


def test_copilot_setup_verifies_act() -> None:
    workflow = (
        REPO_ROOT / ".github" / "workflows" / "copilot-setup-steps.yml"
    ).read_text()
    assert "act" in workflow


# ---------------------------------------------------------------------------
# act dry-run (requires act to be installed; skipped otherwise)
# ---------------------------------------------------------------------------

@pytest.mark.skipif(
    shutil.which("act") is None,
    reason="act is not installed — run .devcontainer/post-start.sh first",
)
def test_act_dry_run_sync_workflow() -> None:
    """act --list must enumerate the sync-from-upstream workflow jobs."""
    result = subprocess.run(
        ["act", "--list", "--workflows", ".github/workflows/sync-from-upstream.yml"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        timeout=60,
    )
    assert result.returncode == 0, (
        f"act --list failed:\nstdout: {result.stdout}\nstderr: {result.stderr}"
    )
    assert "sync" in result.stdout.lower()


@pytest.mark.skipif(
    not (REPO_ROOT / ".github" / "workflows" / "train-prompt.lock.yml").exists(),
    reason=(
        "train-prompt.lock.yml not yet generated — "
        "run .devcontainer/post-start.sh (gh aw add) first"
    ),
)
@pytest.mark.skipif(
    shutil.which("act") is None,
    reason="act is not installed — run .devcontainer/post-start.sh first",
)
def test_act_dry_run_train_prompt_workflow() -> None:
    """act --list must enumerate the train-prompt workflow jobs once the
    lock file has been generated by `gh aw add`."""
    result = subprocess.run(
        ["act", "--list", "--workflows", ".github/workflows/train-prompt.lock.yml"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        timeout=60,
    )
    assert result.returncode == 0, (
        f"act --list failed:\nstdout: {result.stdout}\nstderr: {result.stderr}"
    )
    output_lower = result.stdout.lower()
    assert "activation" in output_lower or "agent" in output_lower
